"""Const-panel null-mode audit (values_prev.json `covariance.null_audit_const`).

Runs engine.null_mode_audit on the prod_gs_const validation predictions
(criterion of the published audit: retained GEVP modes with lambda < 1e-12,
ridge 1e-9, cutoff 1e-7) and writes nullmode_const.json plus a small LaTeX
snippet table of the operator-dictionary decomposition (manuscript line-641
[PENDING-RUN] slot).
"""
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

import config as C
import engine

try:
    from tasks.t_gevp_diag import (_flexcall, _jsonable, _load_state, _pick,
                                   _predict_val)
except ImportError:  # standalone execution (tasks dir not packaged)
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from t_gevp_diag import (_flexcall, _jsonable, _load_state, _pick,
                             _predict_val)

PROVENANCE = "referee-response campaign 2026-06; satelite2/campaign"
N_AUDIT = 256          # published audit sample count (RESULTS_prev.md sec 6.4)


def _tex_escape(s):
    return str(s).replace("_", r"\_")


def _fmt(v):
    if v is None:
        return "---"
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, (int, np.integer)):
        return str(int(v))
    if isinstance(v, (float, np.floating)):
        v = float(v)
        if v != 0.0 and (abs(v) < 1e-3 or abs(v) >= 1e4):
            return f"{v:.3e}"
        return f"{v:.4g}"
    if isinstance(v, (list, tuple)) and len(v) == 2:
        return f"[{_fmt(v[0])}, {_fmt(v[1])}]"
    return _tex_escape(v)


def _latex_table(audit):
    """LaTeX snippet: operator-dictionary decomposition of the null manifold."""
    dictionary = audit.get("dictionary") or []
    # optional per-operator numbers (any numeric list aligned with the dictionary)
    per_op = None
    for k, v in audit.items():
        if k == "dictionary" or not isinstance(v, (list, tuple)):
            continue
        if dictionary and len(v) == len(dictionary) \
                and all(isinstance(x, (int, float)) for x in v):
            per_op = (k, list(v))
            break

    rows = [
        ("null modes per sample (mode)", _pick(audit, "count",
                                               "null_mode_count")),
        ("null-mode count range", _pick(audit, "count_range",
                                        "null_mode_range")),
        ("null modes audited (total)", _pick(audit, "n_modes_total",
                                             "n_modes")),
        (r"$f_{\rm dict}$ median", _pick(audit, "f_dict_med", "f_dict_median")),
        (r"$f_{\rm dict}$ minimum", _pick(audit, "f_dict_min")),
        (r"modes with $f_{\rm dict} > 0.99$", _pick(audit, "count_above_0.99",
                                                    "count_above_099",
                                                    "n_above_0.99")),
    ]

    lines = [
        "% Auto-generated by campaign/tasks/t_nullmode.py",
        f"% {PROVENANCE}",
        "% Operator-dictionary decomposition of the const-panel GEVP null modes",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Operator-dictionary decomposition of the const-panel GEVP",
        "null modes. Criterion: retained modes with $\\lambda < 10^{-12}$",
        "(ridge $10^{-9}$, cutoff $v^{\\dagger}Sv > 10^{-7}$); $f_{\\rm dict}$",
        "is the squared $S$-norm fraction of each null mode inside the",
        "$S$-orthonormalized dictionary span.}",
        "\\label{tab:null_audit_const}",
        "\\begin{tabular}{lr}",
        "\\hline\\hline",
        "quantity & value\\\\",
        "\\hline",
    ]
    for name, val in rows:
        if val is not None:
            lines.append(f"{name} & {_fmt(val)}\\\\")
    if dictionary:
        lines += [
            "\\hline",
            ("dictionary & " +
             "$\\{$" + ", ".join(_tex_escape(d) for d in dictionary) +
             "$\\}$\\\\"),
        ]
    if per_op is not None:
        key, vals = per_op
        lines += ["\\hline",
                  f"% per-operator column: audit key '{key}'"]
        for name, val in zip(dictionary, vals):
            lines.append(f"\\quad {_tex_escape(name)} & {_fmt(val)}\\\\")
    lines += [
        "\\hline\\hline",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    return "\n".join(lines)


def run(out_dir):
    t0 = time.time()
    os.makedirs(out_dir, exist_ok=True)
    engine.init_d20(h_type="const", state_type="gs", beta=C.BETA_GS)
    engine.init_gram()

    n = 8 if C.SMOKE else N_AUDIT
    spec = C.MODELS["prod_gs_const"]
    state = _load_state("prod_gs_const")
    g_true, g_pred = _predict_val("prod_gs_const", spec, state, n, out_dir)
    ns_eff = int(min(n, len(g_pred)))

    audit = _flexcall(engine.null_mode_audit, g_pred, g_true,
                      n_samples=ns_eff, lam_ridge=C.LAMBDA_RIDGE,
                      cutoff=C.SNORM_CUTOFF,
                      lam_pos_threshold=C.LAMBDA_POS_THRESHOLD)
    audit_j = _jsonable(audit) if isinstance(audit, dict) \
        else {"audit": _jsonable(audit)}
    audit_j.setdefault(
        "criterion",
        "retained GEVP modes with lambdas_phys < 1e-12 (zero_tol of the scree "
        "grey band), ridge 1e-9, cutoff v'Sv > 1e-7")

    tex = _latex_table(audit_j)
    tex_path = os.path.join(out_dir, "nullmode_table.tex")
    with open(tex_path, "w") as f:
        f.write(tex)

    result = {
        "task": "nullmode_const",
        "provenance": PROVENANCE,
        "model": "prod_gs_const",
        "n_samples": ns_eff,
        "ridge": C.LAMBDA_RIDGE,
        "cutoff": C.SNORM_CUTOFF,
        "lambda_pos_threshold": C.LAMBDA_POS_THRESHOLD,
        "null_audit_const": audit_j,
        "latex_snippet": tex_path,
        "smoke": bool(C.SMOKE),
        "wall_s": time.time() - t0,
    }
    with open(os.path.join(out_dir, "nullmode_const.json"), "w") as f:
        json.dump(result, f, indent=1)

    return {
        "n_samples": ns_eff,
        "null_count": _jsonable(_pick(audit_j, "count", "null_mode_count")),
        "f_dict_med": _jsonable(_pick(audit_j, "f_dict_med", "f_dict_median")),
        "f_dict_min": _jsonable(_pick(audit_j, "f_dict_min")),
        "count_above_0.99": _jsonable(_pick(audit_j, "count_above_0.99",
                                            "count_above_099",
                                            "n_above_0.99")),
        "latex_snippet": tex_path,
    }
